Librum/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('books/', views.book_list, name='book_list'),
    path('books/<int:book_id>/', views.book_detail, name='book_detail'),
    path('review/<int:review_id>/like/', views.toggle_review_like, name='toggle_review_like'),
    path('books/<int:book_id>/wishlist/', views.wishlist_book, name='wishlist_book'),
    path('books/<int:book_id>/mark-read/', views.mark_book_read, name='mark_book_read'),
    path('books/<int:book_id>/currently-reading/', views.currently_reading_books, name='currently_reading_books'),
    path('books/<int:book_id>/log-progress/', views.log_reading_progress, name='log_reading_progress'),
    path('books/<int:book_id>/total-progress/', views.total_reading_progress, name='total_reading_progress'),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path('profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('profile/', views.my_profile_redirect, name='my_profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from django.utils import timezone

# Create your models here.

class Author(models.Model):
    name = models.TextField(null=True, blank=True)
    surname = models.TextField(null=True, blank=True)
    born = models.DateField(null=True, blank=True)
    place = models.TextField(null=True, blank=True)
    occupation = models.TextField(null=True, blank=True)
    genre = models.TextField(null=True, blank=True)
    notable_works = models.TextField(null=True, blank=True)
    achievements = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} {self.surname}"
    
class Book(models.Model):
    GENRE_CHOICES = [
        ('fantasy', 'Fantasy'),
        ('sci-fi', 'Sci-Fi'),
        ('romance', 'Romance'),
        ('mystery', 'Mystery'),
        ('history', 'History'),
        ('drama', 'Drama'),
        ('thriller', 'Thriller'),
        ('religion', 'Religion'),
        ('crime', 'Crime'),
        ('young adult', 'Young Adult'),
        ('humor', 'Humor'),
        ('adventure', 'Adventure'),
        ('autobiography', 'Autobiography'),
        ('science', 'Science'),
        ('psychology', 'Psychology'),
        ('other', 'Other')
    ]
    title = models.CharField(max_length=200)
    author = models.ManyToManyField(Author, related_name='books')
    genre = models.CharField(max_length=50, choices=GENRE_CHOICES)
    cover_image = models.ImageField(upload_to='books/covers')
    number_of_pages = models.PositiveIntegerField(null=True, blank=True)
    famous_quote = models.TextField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    published_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    def average_rating(self):
        avg = self.ratings.aggregate(Avg('rating'))['rating__avg']
        return round(avg, 1) if avg is not None else 0

    def user_rating(self, user):
        rating = self.ratings.filter(user=user).first()
        return rating.rating if rating else None
    
class BookRating(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()

    class Meta:
        unique_together = ('book', 'user')

    def __str__(self):
        return f"{self.user.username} rated {self.book.title} ({self.rating})"
    
class Review(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user.username} on {self.book.title}"
    
    def total_likes(self):
        return self.reviewlike_set.count()
    
    def is_liked_by(self,user):
        return self.reviewlike_set.filter(user=user).exists()
    
class ReviewLike(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('review', 'user')

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    wishlist_books = models.ManyToManyField(Book, related_name='favorited_by', blank=True)
    read_books = models.ManyToManyField(Book, related_name='read_by', blank=True)
    currently_reading_books = models.ManyToManyField(Book, related_name="currently_reading_by", blank=True)
    image = models.ImageField(upload_to='profile_pics', default='profile_pics/default.jpg')

    def __str__(self):
        return f"{self.user.username}'s Profile"

class ReadingProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    pages_read = models.PositiveIntegerField()
    date = models.DateField(default = timezone.now)

    class Meta:
        pass
    
    def __str__(self):
        return f"{self.user.username} read {self.pages_read} pages of {self.book.title} on {self.date}"

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Librum{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'photo/favicon.png' %}" type="image/png">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link href="https://cdn.jsdelivr.net/npm/nouislider@15.7.0/dist/nouislider.min.css" rel="stylesheet">
</head>
<body>
    <nav>
        <ul class="left-nav">
            <li>
                <a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">
                    <img src="{% static 'photo/logo.png' %}" alt="Home" />
                </a>
            </li>
        </ul>
        <ul class="right-nav">
            <li>
                {% if user.is_authenticated %}
                <a href="{% url 'book_list' %}" class="{% if request.path == '/books/' %}active{% endif %}" title="All Books">
                    <img src="{% static 'photo/bookish.png' %}" alt="Book"/>
                </a>
                {% endif %}
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Account</a>
                <div class="dropdown-content">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="{% if request.path == '/logout/' %}active{% endif %}">Logout</a>
                        <a href="{% url 'user_profile' request.user.id %}">Profile</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="{% if request.path == '/login/' %}active{% endif %}">Login</a>
                        <a href="{% url 'register' %}" class="{% if request.path == '/register/' %}active{% endif %}">Register</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </nav>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <footer></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
<div class="book-details-flex">
    <div id="contentWrapper">

        <div class="book-detail-container">
            <div class="book-detail-card">

                <div class="book-detail-left">
                    <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-detail-image">
                </div>

                <div class="book-detail-right">
                    <h1 class="book-title">{{ book.title }}</h1>

                    <h3 class="book-author">
                        {% for author in book.author.all %}
                            <span id="openAuthorModal" style="cursor:pointer; text-decoration: underline;">
                                {{ author.name }} {{ author.surname }}
                            </span>{% if not forloop.last %}, {% endif %}
                        {% empty %}
                            None
                        {% endfor %}
                    </h3>

                    <p class="book-pages"><strong>Pages:</strong> {{ book.number_of_pages }}</p>
                    <p class="book-genre"><strong>Genre:</strong> {{ book.get_genre_display }}</p>
                    <p class="book-genre"><strong>Published:</strong> {{ book.published_date|date:"F j, Y" }}</p>

                    <button id="openSummaryModal" class="review-submit">Show summary</button>

                    <div class="action-icons">
                     
                        <a href="{% url 'wishlist_book' book.id %}"
                           class="action-icon favorite-icon {% if book in user.userprofile.wishlist_books.all %}filled{% endif %}"
                           title="Add to Wishlist">
                            <svg class="icon" viewBox="0 0 24 24">
                                <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 
                                         2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 
                                         4.5 2.09C13.09 3.81 14.76 3 16.5 3 
                                         19.58 3 22 5.42 22 8.5c0 3.78-3.4 
                                         6.86-8.55 11.54L12 21.35z"/>
                            </svg>
                        </a>

                        <a href="{% url 'mark_book_read' book.id %}"
                           class="action-icon read-icon {% if book in user.userprofile.read_books.all %}filled{% endif %}"
                           title="Mark as Read">
                            <svg class="icon" viewBox="0 0 24 24">
                                <path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 
                                         4.39 6 7.5 11 7.5s9.27-3.11 
                                         11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 
                                         17c-2.76 0-5-2.24-5-5s2.24-5 
                                         5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 
                                         0-3 1.34-3 3s1.34 3 3 3 
                                         3-1.34 3-3-1.34-3-3-3z"/>
                            </svg>
                        </a>

                        <a href="{% url 'currently_reading_books' book.id %}"
                           class="action-icon currently-reading-icon {% if book in user.userprofile.currently_reading_books.all %}filled{% endif %}"
                           title="Add to Currently Reading">
                            <i class="fas fa-book" style="font-size: 20px; color: transparent; -webkit-text-stroke: 1px black;"></i>
                        </a>
                    </div>
                </div>
            </div>
                {% if book.famous_quote %}
                    <blockquote class="book-quote">“{{ book.famous_quote }}”</blockquote>
                {% endif %}
            
        <div class="reviews-display">

            <div class="rating-section">
                <div class="rating-content">
                    {% if user.is_authenticated %}
                        <form method="POST" id="ratingForm" style="margin: 0;">
                            {% csrf_token %}
                            <div class="star-rating">
                                {% for i in "54321" %}
                                    {% with i_int=i|add:0 %}
                                        <input type="radio"
                                               id="star{{ i }}"
                                               name="rating"
                                               value="{{ i }}"
                                               onchange="submitRating()"
                                               {% if user_rating == i_int %}checked{% endif %}
                                               {% if user_rating %}disabled{% endif %}>
                                        <label for="star{{ i }}" title="{{ i }} stars">★</label>
                                    {% endwith %}
                                {% endfor %}
                            </div>
                        </form>
                    {% endif %}
                    <div class="average-rating-text">
                        Average: <span class="average-rating">{{ book.average_rating }}</span>/5
                    </div>
                </div>
            </div>

            <h2>Reviews</h2>
            {% if reviews %}
                {% for review in reviews %}
                    <div class="single-review">
                        <p class="review-author">
                            <strong><a>{{ review.user.username }}</a></strong>:
                        </p>
                        <p class="review-content">{{ review.content }}</p>
                        <p class="review-date">{{ review.created_at|date:"F j, Y, g:i a" }}</p>

                        {% if user.is_authenticated %}
                            <form method="POST" action="{% url 'toggle_review_like' review.id %}">
                                {% csrf_token %}
                                <button type="submit" class="like-button">
                                    {% if review.user_liked %}Unlike{% else %}Like{% endif %}
                                </button>
                                <span>{{ review.total_likes }} like{{ review.total_likes|pluralize }}</span>
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                <p>No reviews yet.</p>
            {% endif %}

            <div class="review-section" style="text-align: center;">
                {% if user.is_authenticated %}
                    <button class="review-submit" id="openReviewModal">Add Review</button>
                {% else %}
                    <p><a href="{% url 'login' %}">Log in</a> to write a review.</p>
                {% endif %}
            </div>
        </div>

        <div class="review-modal" id="summaryModal">
            <div class="review-modal-content">
                <span class="close-modal" id="closeSummaryModal">×</span>
                <h2>{{ book.title }}</h2>
                <p class="author-info">{{ book.summary }}</p>
            </div>
        </div>

        <div class="review-modal" id="authorModal">
        <div class="review-modal-content">
            <span class="close-modal" id="closeAuthorModal">×</span>

            {% for author in book.author.all %}
                <h2><strong>{{ author.name }} {{ author.surname }}</strong></h2><br>
                <p class="author-info"><strong>Born: </strong>{{ author.born }} - {{ author.place }}</p><br>
                <p class="author-info"><strong>Occupation: </strong>{{ author.occupation }}</p><br>
                <p class="author-info"><strong>Genre: </strong>{{ author.genre }}</p><br>
                <p class="author-info"><strong>Notable works: </strong>{{ author.notable_works }}</p><br>
                <p class="author-info"><strong>Achievements: </strong>{{ author.achievements }}</p>
                {% if not forloop.last %}<hr>{% endif %}
            {% empty %}
                <p>No authors available.</p>
            {% endfor %}

        </div>
        </div>

        <div class="review-modal" id="reviewModal">
            <div class="review-modal-content">
                <span class="close-modal" id="closeModal">×</span>
                <h2 class="modal-title">Leave a Review</h2>
                <form method="POST" action="" class="form-container">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="review-submit" name="review_submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

<script src="{% static 'js/book_details.js' %}"></script>
{% endblock %}

app/templates/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Books{% endblock %}

{% block content %}
<div class="book-section-flex">
    <div class="left-panel">
        <div class="search">
            <div class="search-bar">
                <form method="GET" action="" class="search-form">
                    <input type="text" name="q" placeholder="Search..." value="{{ request.GET.q }}">
                    <button type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>

        <div class="filter-box">
            <form method="GET" action="" class="genre-filter-form">
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                
                <div class="sort-box">
                    <label for="sort">Sort by:</label>
                    <select name="sort" id="sort" class="sort-select">
                        <option value="asc" {% if request.GET.sort == 'asc' %}selected{% endif %}>Title Ascending</option>
                        <option value="desc" {% if request.GET.sort == 'desc' %}selected{% endif %}>Title Descending</option>
                        <option value="rating_desc" {% if request.GET.sort_rating == 'rating_desc' %}selected{% endif %}>Highest Rating</option>
                        <option value="rating_asc" {% if request.GET.sort_rating == 'rating_asc' %}selected{% endif %}>Lowest Rating</option>
                    </select>
                </div>

                <label for="genres">Filter by genre:</label><br>
                <div class="genre-columns">
                    <div class="genre-column">
                        {% for genre in genres|slice:":8" %}
                            <label class="genre-checkbox">
                                <input type="checkbox" name="genre" value="{{ genre }}" {% if genre in selected_genres %}checked{% endif %}>
                                {{ genre }}
                            </label>
                        {% endfor %}
                    </div>
                    <div class="genre-column">
                        {% for genre in genres|slice:"8:" %}
                            <label class="genre-checkbox">
                                <input type="checkbox" name="genre" value="{{ genre }}" {% if genre in selected_genres %}checked{% endif %}>
                                {{ genre }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <label for="min_pages" class="filter">Page count:</label><br>
                <input type="number" name="min_pages" placeholder="Min pages" value="{{ min_pages }}"><br>
                <input type="number" name="max_pages" placeholder="Max pages" value="{{ max_pages }}"><br>

                <label for="year-slider" class="filter">Publication year:</label>
                <div id="year-slider" style="margin: 15px 0;"></div>

                <input type="hidden" name="min_year" id="min-year-input" value="{{ min_year }}">
                <input type="hidden" name="max_year" id="max-year-input" value="{{ max_year }}">

                <select name="author" id="author">
                    <option value="">All authors</option>
                    {% for author in authors %}
                        <option value="{{ author.id }}" {% if author.id == selected_author %}selected{% endif %}>{{ author.name }} {{ author.surname }}</option>
                    {% endfor %}
                </select><br><br>

                <button type="submit" class="filter-button">Apply</button>
            </form>
        </div>

        <div class="bookQuote">
            <h2>"Too many books, not enough hours,<br><span style="display:block; padding-left: 30px;">but each one worth the read."</span></h2>
        </div>
    </div>

    <div class="book-list">
        {% for book in books %}
            <div class="book-card">
                <a href="{% url 'book_detail' book.id %}">
                    <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-cover">
                </a>
                <h2>{{ book.title }}</h2>
                <p>{% for author in book.author.all %}
                                {{ author.name }} {{ author.surname }}
                            </span>{% if not forloop.last %}, {% endif %}
                        {% empty %}
                            None
                        {% endfor %}</p>
            </div>
        {% endfor %}

        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}{% for g in selected_genres %}&genre={{ g }}{% endfor %}{% if min_pages %}&min_pages={{ min_pages }}{% endif %}{% if max_pages %}&max_pages={{ max_pages }}{% endif %}{% if min_year %}&min_year={{ min_year }}{% endif %}{% if max_year %}&max_year={{ max_year }}{% endif %}{% if selected_author %}&author={{ selected_author }}{% endif %}">First</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}{% for g in selected_genres %}&genre={{ g }}{% endfor %}{% if min_pages %}&min_pages={{ min_pages }}{% endif %}{% if max_pages %}&max_pages={{ max_pages }}{% endif %}{% if min_year %}&min_year={{ min_year }}{% endif %}{% if max_year %}&max_year={{ max_year }}{% endif %}{% if selected_author %}&author={{ selected_author }}{% endif %}">Previous</a>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}{% for g in selected_genres %}&genre={{ g }}{% endfor %}{% if min_pages %}&min_pages={{ min_pages }}{% endif %}{% if max_pages %}&max_pages={{ max_pages }}{% endif %}{% if min_year %}&min_year={{ min_year }}{% endif %}{% if max_year %}&max_year={{ max_year }}{% endif %}{% if selected_author %}&author={{ selected_author }}{% endif %}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}{% for g in selected_genres %}&genre={{ g }}{% endfor %}{% if min_pages %}&min_pages={{ min_pages }}{% endif %}{% if max_pages %}&max_pages={{ max_pages }}{% endif %}{% if min_year %}&min_year={{ min_year }}{% endif %}{% if max_year %}&max_year={{ max_year }}{% endif %}{% if selected_author %}&author={{ selected_author }}{% endif %}">Last</a>
            {% endif %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/nouislider@15.7.0/dist/nouislider.min.js"></script>
<script src="{% static 'js/slider.js' %}"></script>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}Librum{% endblock %}

{% block content %}
<div class="home">
    <div class="quote-section">
        <blockquote class="quote">
                “A good book is a friend<br>that never lets you down.”  
        </blockquote>
        <p class="quote-text">
                Are you ready to meet your next best friend? 
        </p>
        {% if user.is_authenticated %}
            <a href="{% url 'book_list' %}" class="explore-btn">Explore Our Books</a>
        {% else %}
            <a href="{% url 'login' %}" class="explore-btn">Explore Our Books</a>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% load static %}  

{% block title %}Login{% endblock %}


{% block content %}
<div class="video-section">
    <div class="video-background">
        <video autoplay muted loop>
            <source src="{% static 'video/books.mp4' %}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="login-container container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 mx-auto">
                <div class="login-box">
                    <div class="login-form">
                        <h2>Login</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" id="username" required>
                            </div>

                            <div class="input-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" required>
                            </div>

                            <button type="submit" class="submit-btn">Submit</button>
                        </form>

                        <p class="register-link">You still do not have an account? <a href="{% url 'register' %}"><br>
                            Register here</a></p>

                        {% if messages %}
                            <div class="messages">
                                <ul>
                                    {% for message in messages %}
                                        <li>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% load static %}  

{% block title %}Registration{% endblock %}

{% block content %}
<div class="video-section">
    <div class="video-background">
        <video autoplay muted loop>
            <source src="{% static 'video/books.mp4' %}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="login-container container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="login-box">
                    <h2>Registration</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="input-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.errors %}
                                    <div class="messages">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="submit-btn">Submit</button>
                    </form>

                    <div class="register-link">
                        <p>Do you already have an account? <a href="{% url 'login' %}"><br>
                            Log in here</a></p>
                    </div>
                    {% if messages %}
                        <div class="messages">
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}